title: Ahmad Khanji
logo: /assets/img/headshot_circle.png    
#description: ------
#show_downloads: true
theme: jekyll-theme-minimal
<img src ="img/headshot_circle.png"  style="border-radius: 50%; width: 150px; height:n150px;">
